#
###########################################################
#
# https://github.com/flexdinesh/dev-landing-page
#
###########################################################
#
desc: Minimal landing page for developers.
# indigo-white
# green-white
# red-white
# grey-white
# white-blue
# white-grey
# white-indigo
# white-red
# yellow-black
color: indigo-white
